Document: zouba
Title: Debian zouba Manual
Author: <insert document author here>
Abstract: This manual describes what zouba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zouba/zouba.sgml.gz

Format: postscript
Files: /usr/share/doc/zouba/zouba.ps.gz

Format: text
Files: /usr/share/doc/zouba/zouba.text.gz

Format: HTML
Index: /usr/share/doc/zouba/html/index.html
Files: /usr/share/doc/zouba/html/*.html


